/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublishRouteImport } from './routes/api.publish'
import { Route as ApiAuthLoginRouteImport } from './routes/api.auth.login'
import { Route as ApiAuthLogoutRouteImport } from './routes/api.auth.logout'
import { Route as ApiAuthSessionRouteImport } from './routes/api.auth.session'
import { Route as ApiPublishAssetsRouteImport } from './routes/api.publish.assets'
import { Route as ApiPublishHeadRouteImport } from './routes/api.publish.head'
import { Route as ApiPublishSlugRouteImport } from './routes/api.publish.slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublishRoute = ApiPublishRouteImport.update({
  id: '/api/publish',
  path: '/api/publish',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLoginRoute = ApiAuthLoginRouteImport.update({
  id: '/api/auth/login',
  path: '/api/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLogoutRoute = ApiAuthLogoutRouteImport.update({
  id: '/api/auth/logout',
  path: '/api/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSessionRoute = ApiAuthSessionRouteImport.update({
  id: '/api/auth/session',
  path: '/api/auth/session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublishAssetsRoute = ApiPublishAssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => ApiPublishRoute,
} as any)
const ApiPublishHeadRoute = ApiPublishHeadRouteImport.update({
  id: '/head',
  path: '/head',
  getParentRoute: () => ApiPublishRoute,
} as any)
const ApiPublishSlugRoute = ApiPublishSlugRouteImport.update({
  id: '/slug',
  path: '/slug',
  getParentRoute: () => ApiPublishRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/publish': typeof ApiPublishRouteWithChildren
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/session': typeof ApiAuthSessionRoute
  '/api/publish/assets': typeof ApiPublishAssetsRoute
  '/api/publish/head': typeof ApiPublishHeadRoute
  '/api/publish/slug': typeof ApiPublishSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/publish': typeof ApiPublishRouteWithChildren
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/session': typeof ApiAuthSessionRoute
  '/api/publish/assets': typeof ApiPublishAssetsRoute
  '/api/publish/head': typeof ApiPublishHeadRoute
  '/api/publish/slug': typeof ApiPublishSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/publish': typeof ApiPublishRouteWithChildren
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/session': typeof ApiAuthSessionRoute
  '/api/publish/assets': typeof ApiPublishAssetsRoute
  '/api/publish/head': typeof ApiPublishHeadRoute
  '/api/publish/slug': typeof ApiPublishSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/publish'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/session'
    | '/api/publish/assets'
    | '/api/publish/head'
    | '/api/publish/slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/publish'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/session'
    | '/api/publish/assets'
    | '/api/publish/head'
    | '/api/publish/slug'
  id:
    | '__root__'
    | '/'
    | '/api/publish'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/session'
    | '/api/publish/assets'
    | '/api/publish/head'
    | '/api/publish/slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiPublishRoute: typeof ApiPublishRouteWithChildren
  ApiAuthLoginRoute: typeof ApiAuthLoginRoute
  ApiAuthLogoutRoute: typeof ApiAuthLogoutRoute
  ApiAuthSessionRoute: typeof ApiAuthSessionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/publish': {
      id: '/api/publish'
      path: '/api/publish'
      fullPath: '/api/publish'
      preLoaderRoute: typeof ApiPublishRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/login': {
      id: '/api/auth/login'
      path: '/api/auth/login'
      fullPath: '/api/auth/login'
      preLoaderRoute: typeof ApiAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/logout': {
      id: '/api/auth/logout'
      path: '/api/auth/logout'
      fullPath: '/api/auth/logout'
      preLoaderRoute: typeof ApiAuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/session': {
      id: '/api/auth/session'
      path: '/api/auth/session'
      fullPath: '/api/auth/session'
      preLoaderRoute: typeof ApiAuthSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/publish/assets': {
      id: '/api/publish/assets'
      path: '/assets'
      fullPath: '/api/publish/assets'
      preLoaderRoute: typeof ApiPublishAssetsRouteImport
      parentRoute: typeof ApiPublishRoute
    }
    '/api/publish/head': {
      id: '/api/publish/head'
      path: '/head'
      fullPath: '/api/publish/head'
      preLoaderRoute: typeof ApiPublishHeadRouteImport
      parentRoute: typeof ApiPublishRoute
    }
    '/api/publish/slug': {
      id: '/api/publish/slug'
      path: '/slug'
      fullPath: '/api/publish/slug'
      preLoaderRoute: typeof ApiPublishSlugRouteImport
      parentRoute: typeof ApiPublishRoute
    }
  }
}

interface ApiPublishRouteChildren {
  ApiPublishAssetsRoute: typeof ApiPublishAssetsRoute
  ApiPublishHeadRoute: typeof ApiPublishHeadRoute
  ApiPublishSlugRoute: typeof ApiPublishSlugRoute
}

const ApiPublishRouteChildren: ApiPublishRouteChildren = {
  ApiPublishAssetsRoute: ApiPublishAssetsRoute,
  ApiPublishHeadRoute: ApiPublishHeadRoute,
  ApiPublishSlugRoute: ApiPublishSlugRoute,
}

const ApiPublishRouteWithChildren = ApiPublishRoute._addFileChildren(
  ApiPublishRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiPublishRoute: ApiPublishRouteWithChildren,
  ApiAuthLoginRoute: ApiAuthLoginRoute,
  ApiAuthLogoutRoute: ApiAuthLogoutRoute,
  ApiAuthSessionRoute: ApiAuthSessionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
